# Generated by Django 5.0.2 on 2024-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=60, null=True)),
                ('topic', models.CharField(blank=True, max_length=60, null=True)),
                ('insight', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=600)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('impact', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=350)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
