# Generated by Django 5.0.2 on 2024-03-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pestle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestle_topic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pestle',
        ),
        migrations.RemoveField(
            model_name='article',
            name='region',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.CreateModel(
            name='CountryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.article')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.country')),
            ],
        ),
        migrations.CreateModel(
            name='PestleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.article')),
                ('pestle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.pestle')),
            ],
        ),
        migrations.CreateModel(
            name='RegionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.article')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.region')),
            ],
        ),
        migrations.CreateModel(
            name='SectorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.article')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.sector')),
            ],
        ),
        migrations.CreateModel(
            name='TopicArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.topic')),
            ],
        ),
    ]
