# Generated by Django 5.0.2 on 2024-03-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_country_pestle_region_sector_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pestle',
            old_name='pestle_topic',
            new_name='pestle',
        ),
    ]
