# Generated by Django 5.0.2 on 2024-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_rename_pestle_topic_pestle_pestle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryarticle',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countryarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='pestlearticle',
            name='pestle',
        ),
        migrations.RemoveField(
            model_name='pestlearticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='regionarticle',
            name='region',
        ),
        migrations.RemoveField(
            model_name='regionarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='sectorarticle',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='sectorarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='topicarticle',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicarticle',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pestle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sector',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CountryArticle',
        ),
        migrations.DeleteModel(
            name='Pestle',
        ),
        migrations.DeleteModel(
            name='PestleArticle',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RegionArticle',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='SectorArticle',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicArticle',
        ),
    ]
